name: Build and Deploy2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

# CONFIGURATION
env:
  AZURE_WEBAPP_NAME: appservicedavia
  AZURE_WEBAPP_PACKAGE_PATH: './WebApplication1'
  DOTNET_VERSION: '6.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2

      # Cache .NET Core packages
      - name: Cache .NET Core packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/WebApplication1.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o './output'
          
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './WebApplication1/output'
